version = 0.1
[default.deploy.parameters]
stack_name = "wavepark-reservation-v2"
resolve_s3 = true
s3_prefix = "wavepark-reservation-v2"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
