AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    Runtime: python3.9

Resources:
  ReservationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: wavepark-reservation
      Description: Wavepark 예약 데이터 크롤러
      CodeUri: . # ← 루트 전체를 묶어서 올립니다
      Handler: server.app.handler # ← server/app.py 에서 `handler = Mangum(app)` 으로 export 한 이름
      Events:
        ReservationApi:
          Type: Api
          Properties:
            Path: /reservation/{date}
            Method: GET

Outputs:
  ApiUrl:
    Description: "GET /reservation/{date}"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/reservation/{date}"
